# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10TEBMAFxz7yx5k3tN9KN2o14RB1c7azX
"""

!pip install pandas==2.1.4 matplotlib>=3.8 scikit-learn>=1.4

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import fetch_california_housing

# Load the California Housing dataset
data = fetch_california_housing(as_frame=True)
df = data.frame

# Make a boxplot of median house value
plt.figure(figsize=(8,6))
plt.boxplot(df['MedHouseVal'], vert=True)
plt.title('Boxplot of Median House Value')
plt.ylabel('Value ($100,000s)')

# Save the figure to a local file in Colab
plt.savefig('boxplot.png')
plt.show()
plt.close()